spring:
  banner:
    location: classpath:/config/banner.txt
  jackson:
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false

openapi:
  spec:
    url: api/openapi.yaml

validation:
  exchange:
    paths:
      - path-pattern: /clients/**
        enable-request: true
        enable-response: false
        lenient-mode: false
      - path-pattern: /**
        enable-request: false
        enable-response: false
        lenient-mode: false

# all actuators (JMX, HTTP) are ENABLED by default
## management.endpoints.enabled-by-default: true
## management.endpoints.info.enabled: true
## management.endpoints.health.enabled: true

# all JMX actuators are EXPOSED by default
## management.endpoints.jmx.exposure.exclude:
## management.endpoints.jmx.exposure.include: "*"
## JMX actuators must be secured in production

# For security reasons, only info and health HTTP actuators are EXPOSED by default
## health and info disabled unless listed
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,shutdown
      base-path: /admin

info.blueprint.api.url: https://api.obya.edu/blueprint
