{
  "formatVersion": "1.1",
  "component": {
    "group": "net.serenity-bdd",
    "module": "serenity-gradle-plugin",
    "version": "2.4.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3c4beefrkfa7fllliqf2kqck3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.serenity-bdd",
          "module": "serenity-core",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-model",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-junit",
          "version": {
            "requires": "2.4.24"
          }
        }
      ],
      "files": [
        {
          "name": "serenity-gradle-plugin-2.4.24.jar",
          "url": "serenity-gradle-plugin-2.4.24.jar",
          "size": 34323,
          "sha512": "6425ad23ac6b5b8289d3571d254c4e2acdb3347d3dff118959c88852af5d1c2c3ad3de9100178e474ec4f2645573d72b35ef0538f29fb588da5d67555dfe5af0",
          "sha256": "cc4a847277d9af4cf600d357e50bb24744260461f67639e50c52c19fb4c7b9e0",
          "sha1": "4692d856f551ea92c47cdfb354d42d9ff71458f7",
          "md5": "d9e0f3eb7c17b711a4e51f925ef30581"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.serenity-bdd",
          "module": "serenity-core",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-model",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-junit",
          "version": {
            "requires": "2.4.24"
          }
        }
      ],
      "files": [
        {
          "name": "serenity-gradle-plugin-2.4.24.jar",
          "url": "serenity-gradle-plugin-2.4.24.jar",
          "size": 34323,
          "sha512": "6425ad23ac6b5b8289d3571d254c4e2acdb3347d3dff118959c88852af5d1c2c3ad3de9100178e474ec4f2645573d72b35ef0538f29fb588da5d67555dfe5af0",
          "sha256": "cc4a847277d9af4cf600d357e50bb24744260461f67639e50c52c19fb4c7b9e0",
          "sha1": "4692d856f551ea92c47cdfb354d42d9ff71458f7",
          "md5": "d9e0f3eb7c17b711a4e51f925ef30581"
        }
      ]
    }
  ]
}
