{
  "formatVersion": "1.1",
  "component": {
    "group": "net.serenity-bdd",
    "module": "serenity-gradle-plugin",
    "version": "2.4.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uhdxqbiz4jc5bldx5zm22fqwsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.serenity-bdd",
          "module": "serenity-core",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-model",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-junit",
          "version": {
            "requires": "2.4.24"
          }
        }
      ],
      "files": [
        {
          "name": "serenity-gradle-plugin-2.4.24.jar",
          "url": "serenity-gradle-plugin-2.4.24.jar",
          "size": 34309,
          "sha512": "b0f32f829250a6f5b175451f8c74dc19b84ccadcde5f35b6431480f8fb930e6be84bafe9a08e49a34fcaeccd4bebea1b359e741abbe4c86d75b04b3263b2f0d3",
          "sha256": "702d9df85a3425a2a2490291f59ab10747795469ee1abbd9d582ec52bde440da",
          "sha1": "8dc2ef386b3e9a2d6a7d497f42dc93994b16f833",
          "md5": "c443fb3b8c135a8626383ccd8dec1fbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.serenity-bdd",
          "module": "serenity-core",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-model",
          "version": {
            "requires": "2.4.24"
          }
        },
        {
          "group": "net.serenity-bdd",
          "module": "serenity-junit",
          "version": {
            "requires": "2.4.24"
          }
        }
      ],
      "files": [
        {
          "name": "serenity-gradle-plugin-2.4.24.jar",
          "url": "serenity-gradle-plugin-2.4.24.jar",
          "size": 34309,
          "sha512": "b0f32f829250a6f5b175451f8c74dc19b84ccadcde5f35b6431480f8fb930e6be84bafe9a08e49a34fcaeccd4bebea1b359e741abbe4c86d75b04b3263b2f0d3",
          "sha256": "702d9df85a3425a2a2490291f59ab10747795469ee1abbd9d582ec52bde440da",
          "sha1": "8dc2ef386b3e9a2d6a7d497f42dc93994b16f833",
          "md5": "c443fb3b8c135a8626383ccd8dec1fbf"
        }
      ]
    }
  ]
}
